name: Deploy Docs (gh-pages)

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
      - 'fscheduler/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and Deploy mkdocs to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv pip install --system mkdocs mkdocs-material mkdocstrings mkdocstrings-python pymdown-extensions

      - name: Install package with all extras
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv pip install --system -e '.[all]'

      - name: Build site
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          mkdocs build

      - name: Deploy to gh-pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true